[package]
name = "image_processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
image = "0.25.2"
rayon = "1.10.0"
tokio = { version = "1.40.0", features = ["full"] }
